baseURL = "https://2kabhishek.github.io/blog/"
title = "2KAbhishek Blogs"
copyright = "2KAbhishek"

languageCode = "en"
hasCJKLanguage = true
defaultContentLanguage = "en"

enableRobotsTXT = true
enableEmoji = true

[pagination]
  pagerSize = 8

[module]
  [[module.imports]]
    path = "github.com/2kabhishek/neonote"

[params.author]
  name = "2KAbhishek"
  email = "iam2kabhishek@gmail.com"

[params]
  description = "2KAbhishek's Personal Blog"
  keywords = "blog, technology, programming, computer-science, articles, opensource"
  style = "dark"
  logo = "https://avatars.githubusercontent.com/u/25423853?v=4"
  slogan = "Thoughts of a Passion Driven Developer"

[mediaTypes]
[mediaTypes."text/toml"]
  suffixes = ["toml"]

[outputFormats]
[outputFormats.TOML]
  mediaType = "text/toml"

[outputs]
  home = ["HTML", "RSS", "TOML"]

[params.assets]
  css = ["css/fonts.css", "css/custom.css"]

[params.comments]
  enable = true

[markup.goldmark.renderer]
  unsafe = true

[params.math]
  enable = false

[params.nav]
  showCategories = false
  showTags = false

[taxonomies]
  tag = "tags"

[[params.nav.custom]]
  title = "About"
  url = "https://2kabhishek.github.io/"

[[params.nav.custom]]
  title = "Archives"
  url = "/blog/archives"

[[params.nav.custom]]
  title = "Tags"
  url = "/blog/tags"
